---
- name: restart solr
  service: name=jetty8 state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: set up postgis
  become_user: postgres
  command: "{{ item }}"
  with_items:
    - "psql -d ckan_default -f /usr/share/postgresql/9.5/contrib/postgis-2.2/postgis.sql"
    - "psql -d ckan_default -f /usr/share/postgresql/9.5/contrib/postgis-2.2/spatial_ref_sys.sql"
    - "psql -d ckan_default -c 'ALTER VIEW geometry_columns OWNER TO ckan_default;'"
    - "psql -d ckan_default -c 'ALTER TABLE spatial_ref_sys OWNER TO ckan_default;'"

- name: create ckan database tables
  command: "{{ item }}"
  with_items:
    - "{{ ckan_venv }}/bin/paster --plugin=ckan db init -c {{ ckan_config }} chdir={{ ckan_home }}"
    - "{{ ckan_venv }}/bin/paster --plugin=ckanext-spatial spatial initdb -c {{ ckan_config }} chdir={{ ckan_home }}"
    - "{{ ckan_venv }}/bin/paster --plugin=ckanext-harvest harvester initdb --config={{ ckan_config}} chdir={{ ckan_home }}"
